parameters:
  deploymentMode: ''
  resourceDirectory: ''
  workGroupId: ''
  environment: ''
  azureServiceConnectionName: ''
  location: ''
  resourceGroupUsage: ''

jobs:
- job: ResourceGroupDeployment
  variables:
    templateFilePath: ${{ parameters.resourceDirectory }}\azuredeploy.json
    resourceGroupName: ${{ parameters.workGroupId }}-${{ parameters.location }}-${{ parameters.environment }}-${{ parameters.resourceGroupUsage }}
  pool: 
    vmImage: 'windows-2019'
  steps:
  - task: AzureResourceGroupDeployment@2
    name: ResourceGroupDeployment
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnectionName }}
      action: 'Create Or Update Resource Group'
      resourceGroupName: $(resourceGroupName)
      location: ${{ parameters.location }}
      templateLocation: Linked artifact
      csmFile: $(templateFilePath)
      deploymentMode: ${{ parameters.deploymentMode }}
      deploymentName: $(Build.BuildNumber)

