# Variables to be configured during pipeline creation/execution
# workGroupId
# environment
# location
# azureServiceConnectionName

variables: 
  directory: 'pipeline-execution-app' 
  resourceGroupUsage: 'pipeline-execution'

trigger:
 branches:
   include:
     - master
 paths:
   include:
     - /pipeline-execution-app

stages:
- stage: Deployment
  variables: 
    resourceDirectory: $(Build.Repository.LocalPath)\$(directory)
  jobs:
  - template: ../pipeline-templates/deploy-azure.yml
    parameters: 
      deploymentMode: Incremental
      resourceDirectory: $(resourceDirectory)
      workGroupId: $(workGroupId)
      environment: $(environment)
      azureServiceConnectionName: $(azureServiceConnectionName)
      location: $(location)
      resourceGroupUsage: $(resourceGroupUsage)