# Variables to be configured during pipeline creation/execution
# workGroupId
# environment
# location
# azureServiceConnectionName

variables: 
  directory: 'pipeline-execution-app' 
  resourceGroupUsage: 'pipeline-execution'

trigger: none

stages:
- stage: Validation
  variables: 
    resourceDirectory: $(Build.Repository.LocalPath)\$(directory)
  jobs:
  - template: ../pipeline-templates/deploy-azure.yml
    parameters: 
      deploymentMode: Validation
      resourceDirectory: $(resourceDirectory)
      workGroupId: $(workGroupId)
      environment: $(environment)
      azureServiceConnectionName: $(azureServiceConnectionName)
      location: $(location)
      resourceGroupUsage: $(resourceGroupUsage)